### ISSUE TITLE
Bug NavBar

### ISSUE THREAD

**Issue by Sowness** [Track-1-PP/Tablero#76]
NavBar del índice no tiene la misma estética que los otros y dice “NavBar”

**Comment by TheRaai** [comment]
Esto es conocido, no es un bug, se debe cambiar la clase de la barra.

**Comment by Sowness** [comment]
¿A qué te refieres con que es conocido?

**Comment by TheRaai** [comment]
Ya sabíamos que estaba ese problema, pero se priorizó la utilidad antes de que quedara estandarizado con el resto de las NavBar

**Comment by MarianaNavarroG** [comment]
Arreglado!
